import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>University of Amsterdam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='py-10 text-3xl text-center'>University of Amsterdam</h1>
    </>
  )
}
